/* ===== Nomade Drive Brasil — car catalog =====
   Single source of truth for the detail pages. Adding a car = add one entry here. */
window.CAR_CATALOG = {
  cobalt: {
    id: "cobalt",
    name: "Chevrolet Cobalt Elite",
    year: 2018,
    transmission: "auto",     // "auto" | "manual"
    fipe: 57000,
    tier: "B",
    pilot: true,              // true = our pilot car (badge)
    color: { en: "White", pt: "Branco", es: "Blanco" },
    km: 120000,
    lastRevision: "03/2026",
    tires: 65,                // % of tread left
    body: { en: "Sedan",   pt: "Sedã",          es: "Sedán" },
    seats: 5,
    trunkL: 560,
    features: {
      en: ["Sedan · 5 seats · 560L trunk", "Cheap to maintain", "Roomy for road trips and family", "Reliable GM mid-size"],
      pt: ["Sedã · 5 lugares · porta-malas 560L", "Manutenção barata", "Espaçoso pra viagens e família", "Confiável, GM mid-size"],
      es: ["Sedán · 5 plazas · maletero 560L", "Mantenimiento barato", "Espacioso para viajes y familia", "Confiable, GM mid-size"],
    },
    description: {
      en: "Our pilot car. A 2018 Chevrolet Cobalt Elite, automatic, fully optioned, white. The car we use to test every step of the rental process — so by the time it reaches you, the playbook is solid.",
      pt: "Nosso carro piloto. Chevrolet Cobalt Elite 2018, automático, completo, branco. O carro que usamos pra testar cada passo do processo de locação — quando ele chega na sua mão, tudo já está rodado.",
      es: "Nuestro auto piloto. Chevrolet Cobalt Elite 2018, automático, completo, blanco. El auto con el que probamos cada paso del proceso de alquiler — para cuando llega a vos, todo ya está rodado.",
    },
  },
  hb20: {
    id: "hb20",
    name: "Hyundai HB20 Comfort",
    year: 2019,
    transmission: "manual",
    fipe: 58000,
    tier: "B",
    color: { en: "White", pt: "Branco", es: "Blanco" },
    km: 78000,
    lastRevision: "02/2026",
    tires: 75,
    body: { en: "Compact hatch", pt: "Hatch compacto", es: "Hatch compacto" },
    seats: 5,
    trunkL: 300,
    features: {
      en: ["Compact hatch · 5 seats · fuel efficient", "Easy to park in the city", "Manual gearbox — light to drive", "Solid Hyundai reliability"],
      pt: ["Hatch compacto · 5 lugares · econômico no consumo", "Fácil de estacionar na cidade", "Câmbio manual — leve de dirigir", "Confiabilidade Hyundai"],
      es: ["Hatch compacto · 5 plazas · ahorrador", "Fácil de estacionar en la ciudad", "Caja manual — liviano de manejar", "Confiabilidad Hyundai"],
    },
    description: {
      en: "If you want the cheapest monthly rate and don't mind shifting gears, the HB20 is a smart pick — efficient, easy in traffic, and Hyundai-reliable.",
      pt: "Se você quer a mensal mais barata e topa trocar marcha, o HB20 é uma escolha esperta — econômico, fácil no trânsito e confiável.",
      es: "Si querés la mensual más barata y no te importa pasar cambios, el HB20 es una elección inteligente — eficiente, fácil en el tráfico y confiable.",
    },
  },
  cruze: {
    id: "cruze",
    name: "Chevrolet Cruze LT",
    year: 2018,
    transmission: "auto",
    fipe: 68000,
    tier: "B",
    color: { en: "Silver", pt: "Prata", es: "Plata" },
    km: 95000,
    lastRevision: "01/2026",
    tires: 70,
    body: { en: "Sedan", pt: "Sedã", es: "Sedán" },
    seats: 5,
    trunkL: 480,
    features: {
      en: ["Mid-size sedan · 5 seats", "Highway comfort", "MyLink multimedia", "1.4 turbo · automatic"],
      pt: ["Sedã médio · 5 lugares", "Conforto de estrada", "Multimídia MyLink", "1.4 turbo · automático"],
      es: ["Sedán mediano · 5 plazas", "Confort de ruta", "Multimedia MyLink", "1.4 turbo · automático"],
    },
    description: {
      en: "A step up from the Cobalt — same family of cars, more space, more highway comfort. Great pick for couples and longer trips inside Brazil.",
      pt: "Um upgrade do Cobalt — mesma família, mais espaço, mais conforto de estrada. Boa pedida pra casais e viagens longas dentro do Brasil.",
      es: "Un escalón arriba del Cobalt — misma familia, más espacio, más confort de ruta. Buena elección para parejas y viajes largos por Brasil.",
    },
  },
  cronos: {
    id: "cronos",
    name: "Fiat Cronos Drive 1.3",
    year: 2023,
    transmission: "auto",
    fipe: 78000,
    tier: "B",
    color: { en: "Silver", pt: "Prata", es: "Plata" },
    km: 22000,
    lastRevision: "04/2026",
    tires: 95,
    body: { en: "Compact sedan", pt: "Sedã compacto", es: "Sedán compacto" },
    seats: 5,
    trunkL: 525,
    features: {
      en: ["Compact sedan · 5 seats · fuel efficient", "Multimedia with phone mirror", "Almost-new — 22k km", "Comfortable city + highway combo"],
      pt: ["Sedã compacto · 5 lugares · econômico", "Multimídia com espelhamento", "Quase novo — 22 mil km", "Confortável cidade + estrada"],
      es: ["Sedán compacto · 5 plazas · ahorrador", "Multimedia con espejado", "Casi nuevo — 22 mil km", "Cómodo ciudad + ruta"],
    },
    description: {
      en: "Our newest sedan. Less than 25k km, 2023, automatic. The same car the local agency rents at R$ 4,300/month — here it's R$ 3,510, with 3.000 km/month included.",
      pt: "Nosso sedã mais novo. Menos de 25 mil km, 2023, automático. O mesmo carro que a locadora local cobra R$ 4.300/mês — aqui sai R$ 3.510, com 3.000 km/mês inclusos.",
      es: "Nuestro sedán más nuevo. Menos de 25 mil km, 2023, automático. El mismo auto que la agencia local cobra R$ 4.300/mes — acá sale R$ 3.510, con 3.000 km/mes incluidos.",
    },
  },
  tracker: {
    id: "tracker",
    name: "Chevrolet Tracker LTZ",
    year: 2020,
    transmission: "auto",
    fipe: 95000,
    tier: "C",
    color: { en: "Graphite", pt: "Grafite", es: "Grafito" },
    km: 65000,
    lastRevision: "03/2026",
    tires: 85,
    body: { en: "Compact SUV", pt: "SUV compacto", es: "SUV compacto" },
    seats: 5,
    trunkL: 393,
    features: {
      en: ["Compact SUV · 5 seats · turbo", "Roomy for road trips", "Higher seating · better view", "1.2 turbo · automatic"],
      pt: ["SUV compacto · 5 lugares · turbo", "Espaçoso pra viagens", "Direção mais alta · melhor visão", "1.2 turbo · automático"],
      es: ["SUV compacto · 5 plazas · turbo", "Espacioso para viajes", "Manejo más alto · mejor visión", "1.2 turbo · automático"],
    },
    description: {
      en: "Compact SUV with a higher driving position. Comfortable for road trips, plenty of trunk space, and the turbo handles Brazil's hills with ease.",
      pt: "SUV compacto com direção mais alta. Confortável pra viagens, porta-malas espaçoso e o turbo encara as serras do Brasil tranquilo.",
      es: "SUV compacto con manejo más alto. Cómodo para viajes, maletero espacioso y el turbo encara las sierras de Brasil tranquilo.",
    },
  },
  renegade: {
    id: "renegade",
    name: "Jeep Renegade Sport",
    year: 2020,
    transmission: "auto",
    fipe: 100000,
    tier: "C",
    color: { en: "White", pt: "Branco", es: "Blanco" },
    km: 72000,
    lastRevision: "02/2026",
    tires: 80,
    body: { en: "Compact SUV", pt: "SUV compacto", es: "SUV compacto" },
    seats: 5,
    trunkL: 320,
    features: {
      en: ["Jeep SUV · 5 seats · road-trip ready", "Recognizable Jeep design", "Comfortable suspension", "1.8 flex · automatic"],
      pt: ["SUV Jeep · 5 lugares · pronto pra estrada", "Design Jeep marcante", "Suspensão confortável", "1.8 flex · automático"],
      es: ["SUV Jeep · 5 plazas · listo para ruta", "Diseño Jeep distintivo", "Suspensión cómoda", "1.8 flex · automático"],
    },
    description: {
      en: "The classic Jeep look at a fair monthly rate. Comfortable suspension for Brazil's roads, plenty of cabin space, and that unmistakable Jeep posture.",
      pt: "O visual Jeep clássico numa mensal justa. Suspensão confortável pras estradas do Brasil, cabine espaçosa e aquela postura Jeep inconfundível.",
      es: "El look Jeep clásico a una mensual justa. Suspensión cómoda para las rutas de Brasil, cabina espaciosa y esa postura Jeep inconfundible.",
    },
  },
  corolla: {
    id: "corolla",
    name: "Toyota Corolla XEi",
    year: 2021,
    transmission: "auto",
    fipe: 135000,
    tier: "C",
    color: { en: "Silver", pt: "Prata", es: "Plata" },
    km: 48000,
    lastRevision: "04/2026",
    tires: 90,
    body: { en: "Sedan", pt: "Sedã", es: "Sedán" },
    seats: 5,
    trunkL: 470,
    features: {
      en: ["Premium sedan · 5 seats", "Toyota reliability", "Highway luxury feel", "2.0 flex · CVT automatic"],
      pt: ["Sedã premium · 5 lugares", "Confiabilidade Toyota", "Luxo de estrada", "2.0 flex · automático CVT"],
      es: ["Sedán premium · 5 plazas", "Confiabilidad Toyota", "Lujo de ruta", "2.0 flex · automático CVT"],
    },
    description: {
      en: "The Toyota Corolla XEi — the comfortable, reliable Brazilian executive sedan. If you want a step up in cabin quality and quietness, this is it.",
      pt: "O Toyota Corolla XEi — o sedã executivo brasileiro, confortável e confiável. Se você quer um upgrade em qualidade de cabine e silêncio, é esse.",
      es: "El Toyota Corolla XEi — el sedán ejecutivo brasileño, cómodo y confiable. Si querés un escalón arriba en calidad de cabina y silencio, es este.",
    },
  },
  bmw320: {
    id: "bmw320",
    name: "BMW 320i",
    year: 2023,
    transmission: "auto",
    fipe: 285000,
    tier: "D",
    color: { en: "Black", pt: "Preto", es: "Negro" },
    km: 28000,
    lastRevision: "04/2026",
    tires: 90,
    body: { en: "Luxury sedan", pt: "Sedã luxo", es: "Sedán de lujo" },
    seats: 5,
    trunkL: 480,
    features: {
      en: ["Luxury sedan · 5 seats", "BMW driving feel", "Premium audio + leather", "2.0 turbo · automatic"],
      pt: ["Sedã de luxo · 5 lugares", "Direção BMW", "Som premium + couro", "2.0 turbo · automático"],
      es: ["Sedán de lujo · 5 plazas", "Manejo BMW", "Audio premium + cuero", "2.0 turbo · automático"],
    },
    description: {
      en: "Want a BMW for your stay in Brazil? Here's a 2023 320i — the most accessible BMW sedan, with everything you'd expect from the brand: drive feel, premium cabin, and presence.",
      pt: "Quer uma BMW na sua estadia no Brasil? Aqui está uma 320i 2023 — a BMW sedã mais acessível, com tudo que você espera da marca: direção, cabine premium e presença.",
      es: "¿Querés una BMW en tu estadía en Brasil? Acá tenés una 320i 2023 — la BMW sedán más accesible, con todo lo que esperás de la marca: manejo, cabina premium y presencia.",
    },
  },
  cybertruck: {
    id: "cybertruck",
    name: "Tesla Cybertruck",
    year: 2025,
    transmission: "auto",
    fipe: null,
    tier: "D",
    customPrice: { en: "On request", pt: "Sob consulta", es: "A consultar" },
    color: { en: "Stainless steel", pt: "Aço inox", es: "Acero inox" },
    km: 5000,
    lastRevision: "05/2026",
    tires: 99,
    body: { en: "Electric pickup", pt: "Pickup elétrica", es: "Pickup eléctrica" },
    seats: 5,
    trunkL: 1900,
    features: {
      en: ["Aspirational car · 5 seats · electric", "Tri-motor AWD · 845 hp", "Stainless-steel body", "Talk to us — special terms"],
      pt: ["Carro aspiracional · 5 lugares · elétrica", "Tri-motor AWD · 845 cv", "Carroceria de aço inox", "Fale com a gente — condições especiais"],
      es: ["Auto aspiracional · 5 plazas · eléctrico", "Tri-motor AWD · 845 cv", "Carrocería de acero inox", "Hablá con nosotros — condiciones especiales"],
    },
    description: {
      en: "An aspirational pick — the Cybertruck isn't officially imported in Brazil, but if you want to plan something out of the ordinary, message us. Pricing is custom and depends on availability.",
      pt: "Uma opção aspiracional — a Cybertruck não tem importação oficial no Brasil, mas se você quer planejar algo fora do comum, fala com a gente. Preço sob consulta, depende da disponibilidade.",
      es: "Una opción aspiracional — la Cybertruck no tiene importación oficial en Brasil, pero si querés planear algo fuera de lo común, escribinos. Precio a consultar, depende de la disponibilidad.",
    },
  },
};

window.CAR_ORDER = [
  "cobalt", "hb20", "cruze", "cronos",
  "tracker", "renegade", "corolla", "bmw320", "cybertruck"
];

window.TIER_LABELS = {
  A: { en: "Econômico", pt: "Econômico", es: "Económico" },
  B: { en: "Confort",   pt: "Confort",   es: "Confort"   },
  C: { en: "Premium",   pt: "Premium",   es: "Premium"   },
  D: { en: "Luxo",      pt: "Luxo",      es: "Lujo"      },
};
